-- Database script was generated by Core Lab MySQL Developer
-- Script date 10.01.2018 15:11:17
-- MySQL server version: 5.0.27-community-nt
-- MySQL client version: 4.1
-- ---------------------------------------------------------------------- 
-- Server: localhost
-- Port: 3306
-- Database: simplewebregistrationform

/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Database simplewebregistrationform structure
-- 

USE mysql;

DROP DATABASE IF EXISTS simplewebregistrationform;
CREATE DATABASE simplewebregistrationform;

USE simplewebregistrationform;

-- 
-- Table structure for table registration
-- 
CREATE TABLE `registration` (
  `id` int(11) NOT NULL auto_increment,
  `login` varchar(20) default NULL,
  `password` varchar(20) default NULL,
  `gender` varchar(20) default NULL,
  `year` varchar(20) default NULL,
  `day` varchar(20) default NULL,
  `month` varchar(20) default NULL,
  `name` varchar(20) default NULL,
  `secondname` varchar(20) default NULL,
  `surename` varchar(20) default NULL,
  `email` varchar(20) default NULL,
  `phone` varchar(20) default NULL,
  PRIMARY KEY  (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 
-- Dumping data for table registration
-- 
LOCK TABLES registration WRITE;
INSERT INTO registration VALUES (1, 'ertrt', 'tertert', NULL, NULL, NULL, NULL, 'terter', NULL, 'rtert', 'tert', 'yuty');
INSERT INTO registration VALUES (2, '4534', 'erwer', NULL, NULL, NULL, NULL, 'tert', NULL, 'teryer', 'treryer', 'teyert');
INSERT INTO registration VALUES (3, '3454', '45346', 'Male', '2017', '14', 'May', 'fghfgh', NULL, 'ghfghfg', '537', 'hfgh');
INSERT INTO registration VALUES (4, 'sgsdfgsfdg', 'fgdfgjkjhl', 'Male', '2015', '15', 'Julay', 'dfadsf', NULL, 'dafdaf', 'sfgsfg', 'adfadf');
INSERT INTO registration VALUES (5, '4534', '6666', 'Male', '2004', '6', 'October', 'wer', NULL, 'eger', '5345', '78fds');
INSERT INTO registration VALUES (6, '', '444', 'Male', '2004', '6', 'October', 'wer', NULL, 'eger', '5345', '78fds');
INSERT INTO registration VALUES (7, '', 'zzz', 'Male', '2000', '1', 'January', 'ert', NULL, 'tert', '35', '7687gd');
INSERT INTO registration VALUES (8, '', '123', 'Male', '2015', '28', 'June', 'werwe', NULL, 'wer', 'rter', 'rwer');
INSERT INTO registration VALUES (9, '', 'eqwe', 'Male', '2016', '1', 'January', 'qwe', NULL, 'ryrweq', 'qwe', 'eqwe');
INSERT INTO registration VALUES (10, '', '111', 'Male', '2016', '1', 'January', 'qwe', NULL, 'ryrweq', 'qwe', 'eqwe');
INSERT INTO registration VALUES (11, '', '', 'Male', '2000', '1', 'January', 'qwe', NULL, 'opew', 'wer', 'eqwe');
INSERT INTO registration VALUES (12, '', '', 'Male', '2000', '1', 'January', 'qwe', NULL, 'opew', 'wer', 'eqwe');
INSERT INTO registration VALUES (13, '', '', 'Male', '2000', '1', 'January', 'qwe', NULL, 'opew', 'wer', 'eqwe');
INSERT INTO registration VALUES (14, '', '', 'Male', '2000', '1', 'January', '', NULL, '', '', '');
INSERT INTO registration VALUES (15, '', '', 'Male', '2000', '1', 'January', '', NULL, '', '', '');
INSERT INTO registration VALUES (16, '', '', 'Male', '2000', '1', 'January', '', NULL, '', '', '');
INSERT INTO registration VALUES (17, NULL, '', 'Male', '2000', '1', 'January', NULL, NULL, NULL, NULL, NULL);
INSERT INTO registration VALUES (18, '', '', 'Male', '2000', '1', 'January', '', NULL, '', '', '');
INSERT INTO registration VALUES (19, '', '', 'Male', '2000', '1', 'January', '', NULL, '', '', '');
INSERT INTO registration VALUES (20, 'rwe', '', 'Male', '2000', '1', 'January', '', NULL, '', '', '');
INSERT INTO registration VALUES (21, '342', 'ddd', 'Male', '2000', '1', 'January', 'dsf', NULL, 'fsd', 'wrrwe', 'fsdf');
INSERT INTO registration VALUES (22, 'rwertt', 'rwe', 'Male', '2000', '1', 'January', 'tert', NULL, 'ewrte', 'ewr', 'rwe');
INSERT INTO registration VALUES (23, '534', 'qqq', 'Male', '2000', '1', 'January', 'rew', NULL, 'rtyiuu', '123', 'rtu');
INSERT INTO registration VALUES (24, 'werwe', 'rwe', 'Male', '2000', '1', 'January', 'fsdf', 'sfdfsg', 'kjh', 'ewr', 'wrwe');
INSERT INTO registration VALUES (25, 'werfsd', 'qwerty', 'Male', '2000', '1', 'January', 'dfg', 'gdf', 'fgdfg', 'ewr', 'dgfg');
INSERT INTO registration VALUES (26, '4354', 'qwerty', 'Male', '2000', '1', 'January', 'fdhgfd', 'fghjfgh', 'adsfasd', 'ewr', 'hjghj');
INSERT INTO registration VALUES (27, 'werwet', 'qwerty', 'Male', '2000', '1', 'January', '534', '5345', '5345', 'ewr', '534');
INSERT INTO registration VALUES (28, 'rwer', '111', 'Male', '2000', '1', 'January', 'dfs', 'fsdf', 'fsdf', 'ewr', 'fsd');
INSERT INTO registration VALUES (29, 'ewrwyrt', '111', 'Male', '2000', '1', 'January', 'rwet', 'rwe', 'erwerwer', 'werwe', 'rwe');
INSERT INTO registration VALUES (30, 'rwwe', '111', 'Male', '2000', '1', 'January', 'erw', 'rewe', 'ewrw', '111', 'rwer');
INSERT INTO registration VALUES (31, 'rwwe', '111', 'Male', '2000', '1', 'January', 'erw', 'rewe', 'ewrw', '111', 'rwer');
UNLOCK TABLES;


/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;

