<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="FormToAdminPage.aspx.cs" Inherits="FirstWebsiteDemo.FormToAdminPage" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<title></title>
<link type="text/css" href="CSS/CssBackground.css" rel="stylesheet" />
<link type="text/css" href="CSS/ButonTextFieldsCss.css" rel="stylesheet"/>
<link type="text/css" href="CSS/ScrollCss.css"/ rel="stylesheet" />
<link type="text/css" href="CSS/MenuCss.css" rel="stylesheet" />
<link type="text/css" href="CSS/logoCss.css" rel="stylesheet" />
<style type="text/css">
#btnSave{
    margin-left: 50px;        
    text-align: center;            
    padding: 1px 24px; 
    background-color: rgba(9, 8, 8, 0.7);       
    font-size: 15px;
    color: #fff;
    transition: 0.5s;
}
#btnSave:hover, btn:active{
    background-color: #fff;
    color: #000;  
    transition: 0.5s;
}
#btnAdd{
    margin-left: 3px;        
    text-align: center;            
    padding: 1px 24px; 
    background-color: rgba(9, 8, 8, 0.7);       
    font-size: 15px;
    color: #fff;
    transition: 0.5s;
}
#btnAdd:active, #btnAdd:hover{
    background-color: #fff;
    color: #000;  
    transition: 0.5s;
}
.conteiner{
    background: rgba(55, 52, 52, 0.7);
    position: absolute;
    min-height: 100%;
    top: 79px;
    left: 10%;
    right: 10%;
}
</style>
</head>
<body>
   <form id="form1" runat="server">
    <header>
        <div class="logo"><a href="FormToMainPage.aspx"><img src="img/labelBlack.png" /></a></div>
        <div class="menuRight">
              <nav>
                <ul class="ulReg">
                    <asp:Table runat="server">
                        <asp:TableRow>
                            <asp:TableHeaderCell>
                                <asp:Label ID="lblUser" runat="server"></asp:Label>
                            </asp:TableHeaderCell>
                            <asp:TableHeaderCell>
                                 <asp:Button ID="btnExit" runat="server" Text="Exit" />
                            </asp:TableHeaderCell>
                        </asp:TableRow>
                    </asp:Table>               
                </ul>
              </nav>     
            </div>             
    </header>   
        <div class ="conteiner">           
            <div>
                <asp:GridView ID="gridUsers" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" OnRowDeleting="gridUsers_RowDeleting"
                          OnRowEditing="gridUsers_RowEditing" OnRowUpdating="gridUsers_RowUpdating" AutoGenerateColumns="False" OnRowCancelingEdit="gridUsers_RowCancelingEdit"  EmptyDataText="Table is empty" BackColor="White" BorderColor="#999999" BorderStyle="None" BorderWidth="1px" CellPadding="3" GridLines="Vertical" CausesValidation="false">
                    <AlternatingRowStyle BackColor="#DCDCDC" />
                    <Columns>
                        <asp:TemplateField HeaderText="Id">
                            <ItemTemplate><asp:Label ID="lblId" runat="server" Text='<%#Eval("id") %>'></asp:Label></ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Login">
                            <ItemTemplate><asp:Label ID="lblLogin" runat="server" Text='<%#Eval("login") %>'></asp:Label></ItemTemplate>
                            <EditItemTemplate><asp:TextBox ID="txtLogin" runat="server" Text='<%#Eval("login") %>'></asp:TextBox></EditItemTemplate>
                        </asp:TemplateField>
                          <asp:TemplateField HeaderText="Password">
                            <ItemTemplate><asp:Label ID="lblpassword" runat="server" Text='<%#Eval("password") %>'></asp:Label></ItemTemplate>
                            <EditItemTemplate><asp:TextBox ID="txtPassword" runat="server" Text='<%#Eval("password") %>'></asp:TextBox></EditItemTemplate>
                        </asp:TemplateField>
                          <asp:TemplateField HeaderText="Email">
                            <ItemTemplate><asp:Label ID="lblEmail" runat="server" Text='<%#Eval("email") %>'></asp:Label></ItemTemplate>
                            <EditItemTemplate><asp:TextBox ID="txtEmail" runat="server" Text='<%#Eval("email") %>'></asp:TextBox></EditItemTemplate>
                        </asp:TemplateField>
                          <asp:TemplateField HeaderText="Phone">
                            <ItemTemplate><asp:Label ID="lblPhone" runat="server" Text='<%#Eval("phone") %>'></asp:Label></ItemTemplate>
                            <EditItemTemplate><asp:TextBox ID="txtPhone" runat="server" Text='<%#Eval("phone") %>'></asp:TextBox></EditItemTemplate>
                        </asp:TemplateField>
                          <asp:TemplateField HeaderText="Name">
                            <ItemTemplate><asp:Label ID="lblName" runat="server" Text='<%#Eval("name") %>'></asp:Label></ItemTemplate>
                            <EditItemTemplate><asp:TextBox ID="txtName"  runat="server" Text='<%#Eval("name") %>'></asp:TextBox></EditItemTemplate>
                        </asp:TemplateField>
                          <asp:TemplateField HeaderText="Secondname">
                            <ItemTemplate><asp:Label ID="lblSesondname" runat="server" Text='<%#Eval("secondname") %>'></asp:Label></ItemTemplate>
                            <EditItemTemplate><asp:TextBox ID="txtSecondname" runat="server" Text='<%#Eval("secondname") %>'></asp:TextBox></EditItemTemplate>
                        </asp:TemplateField>
                          <asp:TemplateField HeaderText="Surename">
                            <ItemTemplate><asp:Label ID="lblSurename"  runat="server" Text='<%#Eval("surename") %>'></asp:Label></ItemTemplate>
                            <EditItemTemplate><asp:TextBox ID="txtSurename" runat="server" Text='<%#Eval("surename") %>'></asp:TextBox></EditItemTemplate>
                        </asp:TemplateField>
                          <asp:TemplateField HeaderText="Gender">
                            <ItemTemplate><asp:Label ID="lblGender" runat="server" Text='<%#Eval("gender") %>'></asp:Label></ItemTemplate>
                            <EditItemTemplate> <asp:TextBox ID="txtGender" runat="server" Text='<%#Eval("gender") %>'></asp:TextBox></EditItemTemplate>
                        </asp:TemplateField>
                          <asp:TemplateField HeaderText="Year">
                            <ItemTemplate><asp:Label ID="lblYear"  runat="server" Text='<%#Eval("year") %>'></asp:Label></ItemTemplate>
                            <EditItemTemplate><asp:TextBox ID="txtYear" runat="server" Text='<%#Eval("year") %>'></asp:TextBox></EditItemTemplate>
                        </asp:TemplateField>
                          <asp:TemplateField HeaderText="Day">
                            <ItemTemplate><asp:Label ID="lblDay"  runat="server" Text='<%#Eval("day") %>'></asp:Label></ItemTemplate>
                            <EditItemTemplate><asp:TextBox ID="txtDay"  runat="server" Text='<%#Eval("day") %>'></asp:TextBox></EditItemTemplate>
                        </asp:TemplateField>
                          <asp:TemplateField HeaderText="Month">
                            <ItemTemplate><asp:Label ID="lblMonth"  runat="server" Text='<%#Eval("month") %>'></asp:Label></ItemTemplate>
                            <EditItemTemplate><asp:TextBox ID="txtMonth" runat="server" Text='<%#Eval("month") %>'></asp:TextBox></EditItemTemplate>
                        </asp:TemplateField>
                          <asp:TemplateField HeaderText="Role">
                            <ItemTemplate><asp:Label ID="lblRole" runat="server" Text='<%#Eval("role") %>'></asp:Label></ItemTemplate>
                            <EditItemTemplate><asp:TextBox ID="txtRole" runat="server" Text='<%#Eval("role") %>'></asp:TextBox></EditItemTemplate>
                        </asp:TemplateField>
                    </Columns>
                    <FooterStyle BackColor="#CCCCCC" ForeColor="Black" />
                    <HeaderStyle BackColor="#000084" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
                    <RowStyle BackColor="#EEEEEE" ForeColor="Black" />
                    <SelectedRowStyle BackColor="#008A8C" Font-Bold="True" ForeColor="White" />
                    <SortedAscendingCellStyle BackColor="#F1F1F1" />
                    <SortedAscendingHeaderStyle BackColor="#0000A9" />
                    <SortedDescendingCellStyle BackColor="#CAC9C9" />
                    <SortedDescendingHeaderStyle BackColor="#000065" />
                </asp:GridView>
            </div>
            <div class="userChange">
              <table>
                <tr><td class="text">Login: </td><td><asp:TextBox ID="txtLogin" runat="server" CssClass="txtField" placeholder="Login"></asp:TextBox><hr /></td>
                <td><asp:RequiredFieldValidator ID="reqValidLogin" runat="server"  Display="Dynamic" ControlToValidate="txtLogin" CssClass="color" ErrorMessage="Empty field"></asp:RequiredFieldValidator></td></tr>
                <tr><td class="text">Name: </td><td><asp:TextBox ID="txtName" runat="server" CssClass="txtField" placeholder="Name"></asp:TextBox><hr /></td>
                <td><asp:RequiredFieldValidator ID="reqvalidName" runat="server"  Display="Dynamic" ControlToValidate="txtName" CssClass="color" ErrorMessage="Empty field"></asp:RequiredFieldValidator></td></tr>
                <tr><td class="text">Secondname: </td><td><asp:TextBox ID="txtSecondName" runat="server" CssClass="txtField" placeholder="Secondname"></asp:TextBox><hr /></td>
                <td><asp:RequiredFieldValidator ID="reqvalidSecondname" runat="server"  Display="Dynamic" ControlToValidate="txtSecondName" CssClass="color" ErrorMessage="Empty field"></asp:RequiredFieldValidator></td></tr>
                <tr><td class="text">Surename: </td><td><asp:TextBox ID="txtSurename" runat="server" CssClass="txtField" placeholder="Surename"></asp:TextBox><hr /></td>
                <td><asp:RequiredFieldValidator ID="reqValidSurename" runat="server"  Display="Dynamic" ControlToValidate="txtSurename" CssClass="color" ErrorMessage="Empty field"></asp:RequiredFieldValidator></td></tr>
                <tr><td class="text">Gender: </td><td><asp:TextBox ID="txtGender" runat="server" CssClass="txtField" placeholder="Gender"></asp:TextBox><hr /></td>
                <td><asp:RequiredFieldValidator ID="reqValidGender" runat="server"  Display="Dynamic" ControlToValidate="txtGender" CssClass="color" ErrorMessage="Empty field"></asp:RequiredFieldValidator></td></tr>
                <tr><td class="text">Password: </td><td><asp:TextBox ID="txtPassword" runat="server" CssClass="txtField" placeholder="Password"></asp:TextBox><hr /></td>
                <td><asp:RequiredFieldValidator ID="reqValidPassword" runat="server"  Display="Dynamic" ControlToValidate="txtPassword" CssClass="color" ErrorMessage="Empty field"></asp:RequiredFieldValidator></td></tr>
                <tr><td class="text">Phone: </td><td><asp:TextBox ID="txtPhone" runat="server" CssClass="txtField" placeholder="Phone"></asp:TextBox><hr /></td>
                <td><asp:RequiredFieldValidator ID="reqValidPhone" runat="server"  Display="Dynamic" ControlToValidate="txtPhone" CssClass="color" ErrorMessage="Empty field"></asp:RequiredFieldValidator></td></tr>
                <tr><td class="text">Email: </td><td><asp:TextBox ID="txtEmail" runat="server" CssClass="txtField" placeholder="Email"></asp:TextBox><hr /></td>
                <td><asp:RequiredFieldValidator ID="reqValidEmail" runat="server"  Display="Dynamic" ControlToValidate="txtEmail" CssClass="color" ErrorMessage="Empty field"></asp:RequiredFieldValidator></td></tr>   
                <tr><td class="text">Year: </td><td><asp:TextBox ID="txtYear" runat="server" CssClass="txtField" placeholder="Year"></asp:TextBox><hr /></td>
                <td><asp:RequiredFieldValidator ID="reqValidYear" runat="server"  Display="Dynamic" ControlToValidate="txtYear" CssClass="color" ErrorMessage="Empty field"></asp:RequiredFieldValidator></td></tr>     
                <tr><td class="text">Day: </td><td><asp:TextBox ID="txtDay" runat="server" CssClass="txtField" placeholder="Day"></asp:TextBox><hr /></td>
                <td><asp:RequiredFieldValidator ID="reqValidDay" runat="server"  Display="Dynamic" ControlToValidate="txtDay" CssClass="color" ErrorMessage="Empty field"></asp:RequiredFieldValidator></td></tr>           
                <tr><td class="text">Month: </td><td><asp:TextBox ID="txtMonth" runat="server" CssClass="txtField" placeholder="Month"></asp:TextBox><hr /></td>
                <td><asp:RequiredFieldValidator ID="reqValidMonth" runat="server"  Display="Dynamic" ControlToValidate="txtMonth" CssClass="color" ErrorMessage="Empty field"></asp:RequiredFieldValidator></td></tr>        
                <tr><td><asp:Button ID="btnAdd" runat="server" Text="Insert" OnClick="btnAdd_Click" /></td></tr>
              </table>     
            </div>
        </div>
    </form>
</body>
</html>
